### ISSUE TITLE
Add command to list only local changes

### ISSUE THREAD

**Issue by basti1302** [cliffano/repoman#16]
`repoman changes` is already there to answer the question "For each repo, which local changes do I have?"

I often ask myself a slightly different question: "Do I have any repo that has local changes that needs to be be send to the remote repo?" or more specifically "Did I forget to `git push` in one of my repos?".

To answer that question I would need to parse the output of `repoman changes` carefully, which is tedious and error prone if there are a lot of repos in my `.repoman.json`.

Would you be open to a new command that only lists those repos where something needs to be committed and/or pushed (and completely omits output for any repository that has no local changes)? Maybe it could also be a config option for the existing repoman changes.

**Comment by cliffano** [comment]
Hi @basti1302 

From your description, I think you're trying to identify the changes that are ready to be pushed to remote, but not yet pushed.
I'm in favor of introducing new command to represent this rather than introducing flags.

Which git command do you reckon would be suitable to get such information?
Would this be good enough? git log --branches --not --remotes --oneline

As for the command name, I intended `changes` to represent any type of changes that are made locally, hence it includes both committed and uncommitted changes. (though I'm starting to think that maybe stash should be considered a change).
So for identifying the committed ones, without using any SCM-specific terminology, perhaps `ready-changes` command be suitable? I'm open for better name as long as it doesn't have specific things like uncommitted, local, or remote.

**Comment by basti1302** [comment]
I explained myself badly. The focus for me is not not-pushed changes versus not-committed changes but rather "only list changes" in contrast to "list all repos with their changes".

But since I see that you are generally open to the idea, I thought I put together some real code changes, this might make it easier to discuss. Let's continue the discussion in #17.
